version: "3.8"
services:
  app:
#    build:
#      context: ./
#      dockerfile: Server/Dockerfile
    image: nikole647/pythonproject3-app:latest
    depends_on:
      - db
    networks:
      - my_network
#    volumes:
#      # Mount the 'templates' directory to the '/app/templates' directory inside the container
#      - ./templates:/app/templates

  db:
    image: nikole647/pythonproject3-db
    networks:
      - my_network

networks:
  my_network: