apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.secretName}}
type: Opaque
stringData:
  host: {{.Values.secrets.USERHOST}}
  port: {{.Values.secrets.USERPORT}}
  username: {{.Values.secrets.USERUSER}}
  password: {{.Values.secrets.USERPASS}}
  dbname: {{.Values.secrets.USERDB}}



