apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app.mdname}}
spec:
  replicas: {{.Values.app.replicas}}
  selector:
    matchLabels:
      app: {{.Values.app.name}}
  template:
    metadata:
      labels:
        app: {{.Values.app.name}}
    spec:
      containers:
        - name: {{.Values.app.name}}
          image: nikole647/pythonproject3-app:latest

          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{.Values.secretName}}
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Values.secretName}}
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{.Values.secretName}}
                  key: dbname
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: {{.Values.secretName}}
                  key: host
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: {{.Values.secretName}}
                  key: port
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: {{.Values.app.name}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: {{.Values.appservicetype}}

