apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: animal
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: my-app-chart
    repoURL: 'https://github.com/Nikole647/AnimalShalter.git'
    targetRevision: HEAD
  sources: []
  project: default
