
app:
  mdname: flask-app-deployment
  name: flask-app
  replicas: 1

appservicetype: LoadBalancer


database:
  mdname: databases
  name: databases-db
  replicas: 1
  servicename: databases-service


secretName: thisissodi

secrets:
  USERHOST:    "databases-service"
  USERUSER:    "root"
  USERPASS:    "pass1234"
  USERDB:      "Animal_Shelter"
  USERPORT:    "3306"
