name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Local Test
        run: |
          # Run Docker Compose locally
          docker-compose up -d

          # Wait for a moment to let containers start
          sleep 20

          # Test if the app is running by making a request to 172.28.1.3:5000
          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://172.28.1.3:5000)

          # Exit if response code is not 200
          if [ $response_code -ne 200 ]; then
            echo "Local test failed with response code: $response_code"
            exit 1
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push mysql_db
        uses: docker/build-push-action@v4
        with:
          context: ./DB
          file: ./DB/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mysql:latest

      - name: Build and push app
        uses: docker/build-push-action@v4
        with:
          context: ./Server
          file: ./Server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest
