name: Flask App test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
       python -m pip install --upgrade pip
       pip install -r server/requirements.txt

    - name: Run tests
      run: python3 -m unittest discover tests

    - name: Deploy Flask App in Background
      run: |
        nohup python3 Server/Server.py &
        sleep 10  # Allow some time for the app to start
